import { pool } from '../config/database.js'

export async function findAll() { const [rows] = await pool.execute('SELECT p.*, s.name AS supplier_name, u.name AS user_name FROM purchases p LEFT JOIN suppliers s ON s.id = p.supplier_id LEFT JOIN users u ON u.id = p.user_id ORDER BY p.purchase_date DESC, p.id DESC'); return rows }
export async function findById(id) { const [rows] = await pool.execute('SELECT * FROM purchases WHERE id = ?', [id]); return rows[0] || null }
export async function create(data) { const [result] = await pool.execute('INSERT INTO purchases (code, reference, supplier, supplier_id, purchase_date, total, total_value, observations, status, notes, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [data.code, data.reference || data.code, data.supplier || null, data.supplier_id, data.purchase_date, data.total || data.total_value || 0, data.total_value || data.total || 0, data.observations || null, data.status || 'completed', data.notes || null, data.user_id]); return findById(result.insertId) }
export async function update(id, data) { const [result] = await pool.execute('UPDATE purchases SET code = ?, reference = ?, supplier_id = ?, purchase_date = ?, total = ?, total_value = ?, observations = ?, status = ?, notes = ? WHERE id = ?', [data.code, data.reference || data.code, data.supplier_id, data.purchase_date, data.total || data.total_value || 0, data.total_value || data.total || 0, data.observations || null, data.status || 'completed', data.notes || null, id]); return result.affectedRows ? findById(id) : null }
export async function remove(id) { const [result] = await pool.execute('DELETE FROM purchases WHERE id = ?', [id]); return result.affectedRows > 0 }
export async function addItem(data) { const [result] = await pool.execute('INSERT INTO purchase_items (purchase_id, product_id, quantity, unit_cost) VALUES (?, ?, ?, ?)', [data.purchase_id, data.product_id, data.quantity, data.unit_cost]); return result.insertId }
export async function findItems(purchaseId) { const [rows] = await pool.execute('SELECT pi.*, p.name AS product_name FROM purchase_items pi INNER JOIN products p ON p.id = pi.product_id WHERE pi.purchase_id = ?', [purchaseId]); return rows }
