import { pool } from '../config/database.js'

export async function findAll() { const [rows] = await pool.execute('SELECT s.*, c.full_name AS client_name, u.name AS user_name FROM sales s LEFT JOIN clients c ON c.id = s.client_id LEFT JOIN users u ON u.id = s.user_id ORDER BY s.sale_date DESC, s.id DESC'); return rows }
export async function findById(id) { const [rows] = await pool.execute('SELECT * FROM sales WHERE id = ?', [id]); return rows[0] || null }
export async function create(data) { const [result] = await pool.execute('INSERT INTO sales (code, reference, sale_date, total, total_value, pass, outstanding_balance, notes, client_id, user_id, payment_type, monto_contado, monto_credito, pago_con_credito, estado, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [data.code, data.reference || data.code, data.sale_date, data.total || data.total_value || 0, data.total_value || data.total || 0, data.pass || 0, data.outstanding_balance || 0, data.notes || null, data.client_id, data.user_id, data.payment_type || 'contado', data.monto_contado || data.total || 0, data.monto_credito || 0, data.pago_con_credito || false, data.estado || 'activa', data.status || 'completed']); return findById(result.insertId) }
export async function update(id, data) { const [result] = await pool.execute('UPDATE sales SET code = ?, reference = ?, sale_date = ?, total = ?, total_value = ?, pass = ?, outstanding_balance = ?, notes = ?, client_id = ?, payment_type = ?, monto_contado = ?, monto_credito = ?, pago_con_credito = ?, estado = ?, status = ? WHERE id = ?', [data.code, data.reference || data.code, data.sale_date, data.total || data.total_value || 0, data.total_value || data.total || 0, data.pass || 0, data.outstanding_balance || 0, data.notes || null, data.client_id, data.payment_type || 'contado', data.monto_contado || data.total || 0, data.monto_credito || 0, data.pago_con_credito || false, data.estado || 'activa', data.status || 'completed', id]); return result.affectedRows ? findById(id) : null }
export async function remove(id) { const [result] = await pool.execute('DELETE FROM sales WHERE id = ?', [id]); return result.affectedRows > 0 }
export async function addItem(data) { const [result] = await pool.execute('INSERT INTO sale_items (sale_id, product_id, quantity, unit_price) VALUES (?, ?, ?, ?)', [data.sale_id, data.product_id, data.quantity, data.unit_price]); return result.insertId }
export async function findItems(saleId) { const [rows] = await pool.execute('SELECT si.*, p.name AS product_name FROM sale_items si INNER JOIN products p ON p.id = si.product_id WHERE si.sale_id = ?', [saleId]); return rows }
