import * as Compra from '../models/compra_model.js'

export async function getPurchases(req, res, next) { try { const purchases = await Compra.findAll(); res.json({ ok: true, count: purchases.length, purchases }) } catch (error) { next(error) } }
export async function getPurchaseById(req, res, next) { try { const purchase = await Compra.findById(req.params.id); if (!purchase) return res.status(404).json({ ok: false, msg: 'Compra no encontrada' }); res.json({ ok: true, purchase }) } catch (error) { next(error) } }
export async function createPurchase(req, res, next) { try { const { code, supplier_id, purchase_date } = req.body; if (!code || !supplier_id || !purchase_date) return res.status(400).json({ ok: false, msg: 'code, supplier_id y purchase_date son obligatorios' }); const purchase = await Compra.create({ ...req.body, user_id: req.user.id }); res.status(201).json({ ok: true, purchase }) } catch (error) { next(error) } }
export async function updatePurchase(req, res, next) { try { const purchase = await Compra.update(req.params.id, req.body); if (!purchase) return res.status(404).json({ ok: false, msg: 'Compra no encontrada' }); res.json({ ok: true, purchase }) } catch (error) { next(error) } }
export async function deletePurchase(req, res, next) { try { if (!await Compra.remove(req.params.id)) return res.status(404).json({ ok: false, msg: 'Compra no encontrada' }); res.json({ ok: true, msg: 'Compra eliminada' }) } catch (error) { next(error) } }
export async function addPurchaseItem(req, res, next) { try { const { product_id, quantity, unit_cost } = req.body; if (!product_id || !quantity || unit_cost === undefined) return res.status(400).json({ ok: false, msg: 'product_id, quantity y unit_cost son obligatorios' }); const id = await Compra.addItem({ purchase_id: req.params.id, product_id, quantity, unit_cost }); res.status(201).json({ ok: true, itemId: id }) } catch (error) { next(error) } }
export async function getPurchaseItems(req, res, next) { try { res.json({ ok: true, items: await Compra.findItems(req.params.id) }) } catch (error) { next(error) } }
