import * as Venta from '../models/venta_model.js'

export async function getSales(req, res, next) { try { const sales = await Venta.findAll(); res.json({ ok: true, count: sales.length, sales }) } catch (error) { next(error) } }
export async function getSaleById(req, res, next) { try { const sale = await Venta.findById(req.params.id); if (!sale) return res.status(404).json({ ok: false, msg: 'Venta no encontrada' }); res.json({ ok: true, sale }) } catch (error) { next(error) } }
export async function createSale(req, res, next) { try { const { code, client_id, sale_date, payment_type } = req.body; if (!code || !client_id || !sale_date || !payment_type) return res.status(400).json({ ok: false, msg: 'code, client_id, sale_date y payment_type son obligatorios' }); const sale = await Venta.create({ ...req.body, user_id: req.user.id }); res.status(201).json({ ok: true, sale }) } catch (error) { next(error) } }
export async function updateSale(req, res, next) { try { const sale = await Venta.update(req.params.id, req.body); if (!sale) return res.status(404).json({ ok: false, msg: 'Venta no encontrada' }); res.json({ ok: true, sale }) } catch (error) { next(error) } }
export async function deleteSale(req, res, next) { try { if (!await Venta.remove(req.params.id)) return res.status(404).json({ ok: false, msg: 'Venta no encontrada' }); res.json({ ok: true, msg: 'Venta eliminada' }) } catch (error) { next(error) } }
export async function addSaleItem(req, res, next) { try { const { product_id, quantity, unit_price } = req.body; if (!product_id || !quantity || unit_price === undefined) return res.status(400).json({ ok: false, msg: 'product_id, quantity y unit_price son obligatorios' }); const id = await Venta.addItem({ sale_id: req.params.id, product_id, quantity, unit_price }); res.status(201).json({ ok: true, itemId: id }) } catch (error) { next(error) } }
export async function getSaleItems(req, res, next) { try { res.json({ ok: true, items: await Venta.findItems(req.params.id) }) } catch (error) { next(error) } }
